version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/temp-django-notes-app  # Temporary 
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ubuntu

