version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/django-notes-app
permissions:
  - object: /home/ubuntu/django-notes-app
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      runas: ubuntu
